<?php

namespace BlogBundle\Repository;

/**
 * BegeniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BegeniRepository extends \Doctrine\ORM\EntityRepository
{
}
