<?php

namespace BlogBundle\Repository;

/**
 * TakipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TakipRepository extends \Doctrine\ORM\EntityRepository
{
}
