<?php

namespace BlogBundle\Repository;

/**
 * U_Y_BRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class U_Y_BRepository extends \Doctrine\ORM\EntityRepository
{
}
