<?php

namespace BlogBundle\Repository;

/**
 * YaziRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YaziRepository extends \Doctrine\ORM\EntityRepository
{
}
