blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

blog_yazi_ekle:
    path:     /yazi-ekle
    defaults: { _controller: BlogBundle:Default:yaziEkle }


blog_yazi_sil:
    path:     /{id}/yazi-sil
    defaults: { _controller: BlogBundle:Default:yaziSil}

blog_yazi_yorum:
    path:     /yorum-ekle
    defaults: { _controller: BlogBundle:Default:yorumEkle }

blog_yorum_sil:
    path:     /{id}/yorum-sil
    defaults: { _controller: BlogBundle:Default:yorumSil }

blog_yazi_begen:
    path:     /{id}/yazi-begen
    defaults: { _controller: BlogBundle:Default:yaziBegen }

blog_yazi_unlike:
    path:     /{id}/yazi-unlike
    defaults: { _controller: BlogBundle:Default:yaziUnlike }

blog_profil:
    path:     /{id}/profil
    defaults: { _controller: BlogBundle:Default:profil }

